-- ============================================================
-- 0005_crm_core.sql
-- Core CRM entities: companies, leads, contacts, customers,
-- vendors, deals, pipelines, tasks, notes, activities, custom fields
-- ============================================================

-- ---------- Companies (organizations a lead/contact/customer belongs to) ----------
create table public.companies (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  name        text not null,
  website     text,
  industry    text,
  phone       text,
  city        text,
  is_deleted  boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index idx_companies_tenant on public.companies (tenant_id);

-- ---------- Vendors ----------
create table public.vendors (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  name        text not null,
  email       text,
  phone       text,
  category    text,
  notes       text,
  is_deleted  boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index idx_vendors_tenant on public.vendors (tenant_id);

-- ---------- Lead sources & labels (tenant-configurable dropdowns) ----------
create table public.lead_sources (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references public.tenants(id) on delete cascade,
  name       text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  unique (tenant_id, name)
);

create table public.lead_labels (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references public.tenants(id) on delete cascade,
  name       text not null,
  color      text not null default '#3b82f6',
  created_at timestamptz not null default now(),
  unique (tenant_id, name)
);

-- ---------- Leads ----------
create table public.leads (
  id              uuid primary key default gen_random_uuid(),
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  display_id      text not null,              -- human friendly e.g. LEAD-0001, generated by trigger
  customer_name   text not null,
  phone           text not null,
  email           text,
  city            text,
  company_id      uuid references public.companies(id) on delete set null,
  lead_type       text default 'General',
  amount          numeric(14,2) not null default 0,
  source          text default 'Website',
  label_id        uuid references public.lead_labels(id) on delete set null,
  status          text not null default 'New',   -- New, Contacted, Qualified, Converted, Lost
  assigned_to_id  uuid references public.profiles(id) on delete set null,
  notes           text,
  next_follow_up  timestamptz,
  is_deleted      boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (tenant_id, display_id)
);
create index idx_leads_tenant on public.leads (tenant_id);
create index idx_leads_assigned on public.leads (assigned_to_id);
create index idx_leads_status on public.leads (tenant_id, status);
create index idx_leads_name_trgm on public.leads using gin (customer_name gin_trgm_ops);
create index idx_leads_phone on public.leads (phone);

create table public.lead_activities (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references public.tenants(id) on delete cascade,
  lead_id    uuid not null references public.leads(id) on delete cascade,
  type       text not null,      -- STATUS_CHANGE, CALL, EMAIL, NOTE, ASSIGNMENT
  title      text not null,
  details    text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index idx_lead_activities_lead on public.lead_activities (lead_id);

create table public.follow_ups (
  id            uuid primary key default gen_random_uuid(),
  tenant_id     uuid not null references public.tenants(id) on delete cascade,
  lead_id       uuid not null references public.leads(id) on delete cascade,
  title         text not null,
  scheduled_at  timestamptz not null,
  status        text not null default 'Pending', -- Pending, Done, Missed
  notes         text,
  created_by    uuid references public.profiles(id) on delete set null,
  created_at    timestamptz not null default now()
);
create index idx_followups_lead on public.follow_ups (lead_id);
create index idx_followups_tenant on public.follow_ups (tenant_id, scheduled_at);

-- ---------- Customers (converted leads / existing accounts) ----------
create table public.customers (
  id              uuid primary key default gen_random_uuid(),
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  display_id      text not null,
  name            text not null,
  email           text not null,
  phone           text not null,
  city            text,
  company_id      uuid references public.companies(id) on delete set null,
  status          text not null default 'Active',
  owner_id        uuid references public.profiles(id) on delete set null,
  total_deals     integer not null default 0,
  lifetime_value  numeric(14,2) not null default 0,
  is_deleted      boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (tenant_id, display_id)
);
create index idx_customers_tenant on public.customers (tenant_id);
create index idx_customers_owner on public.customers (owner_id);
create index idx_customers_name_trgm on public.customers using gin (name gin_trgm_ops);

-- ---------- Contacts (people, linked to a lead, customer, and/or company) ----------
create table public.contacts (
  id           uuid primary key default gen_random_uuid(),
  tenant_id    uuid not null references public.tenants(id) on delete cascade,
  name         text not null,
  email        text,
  phone        text,
  designation  text,
  company_id   uuid references public.companies(id) on delete set null,
  lead_id      uuid references public.leads(id) on delete cascade,
  customer_id  uuid references public.customers(id) on delete cascade,
  owner_id     uuid references public.profiles(id) on delete set null,
  is_deleted   boolean not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index idx_contacts_tenant on public.contacts (tenant_id);
create index idx_contacts_lead on public.contacts (lead_id);
create index idx_contacts_customer on public.contacts (customer_id);

-- ---------- Pipelines & stages ----------
create table public.pipelines (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references public.tenants(id) on delete cascade,
  name       text not null default 'Standard Sales Pipeline',
  is_default boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.pipeline_stages (
  id          uuid primary key default gen_random_uuid(),
  pipeline_id uuid not null references public.pipelines(id) on delete cascade,
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  name        text not null,
  stage_key   text not null,
  sort_order  integer not null default 0,
  color       text not null default '#3b82f6',
  probability integer not null default 20,
  created_at  timestamptz not null default now()
);
create index idx_stages_pipeline on public.pipeline_stages (pipeline_id, sort_order);

-- ---------- Deals ----------
create table public.deals (
  id             uuid primary key default gen_random_uuid(),
  tenant_id      uuid not null references public.tenants(id) on delete cascade,
  title          text not null,
  amount         numeric(14,2) not null default 0,
  pipeline_id    uuid not null references public.pipelines(id) on delete cascade,
  stage_id       uuid not null references public.pipeline_stages(id),
  lead_id        uuid references public.leads(id) on delete set null,
  customer_id    uuid references public.customers(id) on delete set null,
  owner_id       uuid references public.profiles(id) on delete set null,
  status         text not null default 'OPEN', -- OPEN, WON, LOST
  expected_close date,
  is_deleted     boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index idx_deals_tenant on public.deals (tenant_id);
create index idx_deals_stage on public.deals (stage_id);
create index idx_deals_owner on public.deals (owner_id);

-- ---------- Custom fields (per-tenant schema-less extensions) ----------
create table public.custom_fields (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  entity_type text not null,   -- 'lead' | 'customer' | 'deal' | 'contact'
  field_name  text not null,
  field_key   text not null,
  field_type  text not null default 'text', -- text, number, date, select, boolean
  options     jsonb,
  is_required boolean not null default false,
  created_at  timestamptz not null default now(),
  unique (tenant_id, entity_type, field_key)
);

create table public.custom_field_values (
  id              uuid primary key default gen_random_uuid(),
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  custom_field_id uuid not null references public.custom_fields(id) on delete cascade,
  lead_id         uuid references public.leads(id) on delete cascade,
  customer_id     uuid references public.customers(id) on delete cascade,
  deal_id         uuid references public.deals(id) on delete cascade,
  contact_id      uuid references public.contacts(id) on delete cascade,
  value           text,
  created_at      timestamptz not null default now()
);
create index idx_cfv_field on public.custom_field_values (custom_field_id);

-- ---------- Tasks ----------
create table public.tasks (
  id             uuid primary key default gen_random_uuid(),
  tenant_id      uuid not null references public.tenants(id) on delete cascade,
  title          text not null,
  description    text,
  priority       text not null default 'Medium', -- Low, Medium, High, Urgent
  status         text not null default 'Pending', -- Pending, In Progress, Completed
  due_date       timestamptz not null,
  assigned_to_id uuid not null references public.profiles(id),
  lead_id        uuid references public.leads(id) on delete cascade,
  deal_id        uuid references public.deals(id) on delete cascade,
  customer_id    uuid references public.customers(id) on delete cascade,
  completed_at   timestamptz,
  created_by     uuid references public.profiles(id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index idx_tasks_tenant on public.tasks (tenant_id);
create index idx_tasks_assigned on public.tasks (assigned_to_id, status);
create index idx_tasks_due on public.tasks (due_date);

-- ---------- Notes ----------
create table public.notes (
  id           uuid primary key default gen_random_uuid(),
  tenant_id    uuid not null references public.tenants(id) on delete cascade,
  content      text not null,
  lead_id      uuid references public.leads(id) on delete cascade,
  customer_id  uuid references public.customers(id) on delete cascade,
  deal_id      uuid references public.deals(id) on delete cascade,
  created_by   uuid not null references public.profiles(id),
  created_at   timestamptz not null default now()
);
create index idx_notes_lead on public.notes (lead_id);
create index idx_notes_customer on public.notes (customer_id);

-- ---------- Activities (generic activity/timeline feed) ----------
create table public.activities (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  title       text not null,
  details     text,
  type        text not null default 'INFO',
  entity_type text,   -- 'lead' | 'deal' | 'customer' | 'task' ...
  entity_id   uuid,
  user_id     uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);
create index idx_activities_tenant on public.activities (tenant_id, created_at desc);
create index idx_activities_entity on public.activities (entity_type, entity_id);
